#!/usr/bin/env bash
set -euo pipefail

OUT_FILE="${1:-./config/local-model.auto.env}"
mkdir -p "$(dirname "$OUT_FILE")"

platform="linux"
if [[ "$(uname -s)" == "Darwin" ]]; then
  platform="macos"
fi
if grep -qi microsoft /proc/version 2>/dev/null; then
  platform="wsl2"
fi

arch="$(uname -m)"
ram_gb="0"
if [[ "$platform" == "macos" ]]; then
  ram_bytes="$(sysctl -n hw.memsize 2>/dev/null || echo 0)"
  ram_gb="$(( ram_bytes / 1024 / 1024 / 1024 ))"
else
  ram_kb="$(awk '/MemTotal/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)"
  ram_gb="$(( ram_kb / 1024 / 1024 ))"
fi

vram_mb="0"
if command -v nvidia-smi >/dev/null 2>&1; then
  vram_mb="$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -n1 | tr -d ' ' || echo 0)"
fi
vram_gb="$(( vram_mb / 1024 ))"

profile="nemotron3-nano-4b-q4km-cpu-safe"
model_id="nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF"
model_family="Nemotron 3 Nano 4B"
quant="Q4_K_M"
runtime="llama.cpp"
mode="cpu"
reason="safe default for low-memory or non-NVIDIA hosts"
cloud_fallback="true"

if [[ "$platform" == "wsl2" || "$platform" == "linux" ]]; then
  if [[ "$vram_gb" -ge 20 ]]; then
    profile="nemotron3-nano-30b-a3b-q3kl-hybrid"
    model_id="nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16"
    model_family="Nemotron 3 Nano 30B-A3B"
    quant="Q3_K_L"
    runtime="llama.cpp"
    mode="hybrid"
    reason="NVIDIA GPU with enough VRAM for a practical 30B hybrid profile"
  elif [[ "$vram_gb" -ge 12 ]]; then
    profile="nemotron3-nano-4b-q4km-gpu"
    model_id="nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF"
    model_family="Nemotron 3 Nano 4B"
    quant="Q4_K_M"
    runtime="llama.cpp"
    mode="gpu"
    reason="NVIDIA GPU detected but not enough VRAM for the heavier 30B profile"
  fi
fi

if [[ "$platform" == "macos" ]]; then
  if [[ "$arch" == "arm64" && "$ram_gb" -ge 24 ]]; then
    reason="macOS default kept conservative for easy local setup and broad compatibility"
  elif [[ "$arch" == "x86_64" ]]; then
    reason="Intel macOS safe default; keep the local model small"
  fi
fi

cat > "$OUT_FILE" <<EOF
# Auto-generated by scripts/detect-local-model.sh
BMO_LOCAL_MODEL_PROFILE=$profile
BMO_LOCAL_MODEL_ID=$model_id
BMO_LOCAL_MODEL_FAMILY=$model_family
BMO_LOCAL_MODEL_QUANT=$quant
BMO_LOCAL_MODEL_RUNTIME=$runtime
BMO_LOCAL_MODEL_MODE=$mode
BMO_LOCAL_MODEL_PLATFORM=$platform
BMO_LOCAL_MODEL_ARCH=$arch
BMO_LOCAL_MODEL_RAM_GB=$ram_gb
BMO_LOCAL_MODEL_VRAM_GB=$vram_gb
BMO_LOCAL_MODEL_REASON=$reason
BMO_LOCAL_MODEL_CLOUD_FALLBACK=$cloud_fallback
EOF

echo "Wrote $OUT_FILE"
cat "$OUT_FILE"
