param(
  [string]$OutFile = ".\config\local-model.auto.env"
)

$ErrorActionPreference = 'Stop'

$platform = 'windows'
$arch = $env:PROCESSOR_ARCHITECTURE
$ramBytes = (Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory
$ramGb = [math]::Floor($ramBytes / 1GB)

$vramMb = 0
try {
  $gpuLines = & nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>$null
  if ($gpuLines) {
    $first = ($gpuLines | Select-Object -First 1).ToString().Trim()
    if ($first) { $vramMb = [int]$first }
  }
} catch {
  $vramMb = 0
}
$vramGb = [math]::Floor($vramMb / 1024)

$profile = 'nemotron3-nano-4b-q4km-cpu-safe'
$modelId = 'nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF'
$modelFamily = 'Nemotron 3 Nano 4B'
$quant = 'Q4_K_M'
$runtime = 'llama.cpp'
$mode = 'cpu'
$reason = 'safe default for low-memory or non-NVIDIA hosts'
$cloudFallback = 'true'

if ($vramGb -ge 20) {
  $profile = 'nemotron3-nano-30b-a3b-q3kl-hybrid'
  $modelId = 'nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16'
  $modelFamily = 'Nemotron 3 Nano 30B-A3B'
  $quant = 'Q3_K_L'
  $runtime = 'llama.cpp'
  $mode = 'hybrid'
  $reason = 'NVIDIA GPU with enough VRAM for a practical 30B hybrid profile'
} elseif ($vramGb -ge 12) {
  $profile = 'nemotron3-nano-4b-q4km-gpu'
  $modelId = 'nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF'
  $modelFamily = 'Nemotron 3 Nano 4B'
  $quant = 'Q4_K_M'
  $runtime = 'llama.cpp'
  $mode = 'gpu'
  $reason = 'NVIDIA GPU detected but not enough VRAM for the heavier 30B profile'
}

$dir = Split-Path $OutFile -Parent
if ($dir) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

@(
  '# Auto-generated by scripts/detect-local-model.ps1'
  "BMO_LOCAL_MODEL_PROFILE=$profile"
  "BMO_LOCAL_MODEL_ID=$modelId"
  "BMO_LOCAL_MODEL_FAMILY=$modelFamily"
  "BMO_LOCAL_MODEL_QUANT=$quant"
  "BMO_LOCAL_MODEL_RUNTIME=$runtime"
  "BMO_LOCAL_MODEL_MODE=$mode"
  "BMO_LOCAL_MODEL_PLATFORM=$platform"
  "BMO_LOCAL_MODEL_ARCH=$arch"
  "BMO_LOCAL_MODEL_RAM_GB=$ramGb"
  "BMO_LOCAL_MODEL_VRAM_GB=$vramGb"
  "BMO_LOCAL_MODEL_REASON=$reason"
  "BMO_LOCAL_MODEL_CLOUD_FALLBACK=$cloudFallback"
) | Set-Content -Path $OutFile -Encoding UTF8

Write-Host "Wrote $OutFile"
Get-Content $OutFile
