#!/usr/bin/env bash
set -euo pipefail

REPO_URL="https://github.com/codysumpter-cloud/bmo-stack.git"
ARCHIVE_URL="https://github.com/codysumpter-cloud/bmo-stack/archive/refs/heads/master.tar.gz"
REPO_DIR="${BMO_STACK_DIR:-$HOME/.bmo-stack}"
OPENCLAW_PREFIX="${OPENCLAW_PREFIX:-$HOME/.openclaw}"

say() {
  printf '\n== %s ==\n' "$1"
}

have_cmd() {
  command -v "$1" >/dev/null 2>&1
}

ensure_repo() {
  say "Preparing bmo-stack repo"
  if have_cmd git; then
    if [[ -d "$REPO_DIR/.git" ]]; then
      git -C "$REPO_DIR" pull --ff-only || true
    else
      mkdir -p "$(dirname "$REPO_DIR")"
      git clone "$REPO_URL" "$REPO_DIR"
    fi
  else
    mkdir -p "$REPO_DIR"
    tmpdir="$(mktemp -d)"
    trap 'rm -rf "$tmpdir"' EXIT
    curl -fsSL "$ARCHIVE_URL" -o "$tmpdir/bmo-stack.tar.gz"
    tar -xzf "$tmpdir/bmo-stack.tar.gz" -C "$tmpdir"
    rm -rf "$REPO_DIR"
    mv "$tmpdir/bmo-stack-master" "$REPO_DIR"
  fi
}

write_local_model_auto_env() {
  say "Selecting local model profile"
  out_file="$REPO_DIR/config/local-model.auto.env"
  mkdir -p "$(dirname "$out_file")"

  platform="linux"
  if [[ "$(uname -s)" == "Darwin" ]]; then
    platform="macos"
  fi
  if grep -qi microsoft /proc/version 2>/dev/null; then
    platform="wsl2"
  fi

  arch="$(uname -m)"
  if [[ "$platform" == "macos" ]]; then
    ram_bytes="$(sysctl -n hw.memsize 2>/dev/null || echo 0)"
    ram_gb="$(( ram_bytes / 1024 / 1024 / 1024 ))"
  else
    ram_kb="$(awk '/MemTotal/ {print $2}' /proc/meminfo 2>/dev/null || echo 0)"
    ram_gb="$(( ram_kb / 1024 / 1024 ))"
  fi

  vram_mb="0"
  if have_cmd nvidia-smi; then
    vram_mb="$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -n1 | tr -d ' ' || echo 0)"
  fi
  vram_gb="$(( vram_mb / 1024 ))"

  profile="nemotron3-nano-4b-q4km-cpu-safe"
  model_id="nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF"
  model_family="Nemotron 3 Nano 4B"
  quant="Q4_K_M"
  runtime="llama.cpp"
  mode="cpu"
  reason="safe default for low-memory or non-NVIDIA hosts"
  cloud_fallback="true"

  if [[ "$platform" == "wsl2" || "$platform" == "linux" ]]; then
    if [[ "$vram_gb" -ge 16 ]]; then
      profile="nemotron3-nano-30b-a3b-q3kl-hybrid"
      model_id="nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16"
      model_family="Nemotron 3 Nano 30B-A3B"
      quant="Q3_K_L"
      runtime="llama.cpp"
      mode="hybrid"
      reason="NVIDIA GPU with enough VRAM for a practical 30B hybrid profile"
    elif [[ "$vram_gb" -ge 12 ]]; then
      profile="nemotron3-nano-4b-q4km-gpu"
      model_id="nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF"
      model_family="Nemotron 3 Nano 4B"
      quant="Q4_K_M"
      runtime="llama.cpp"
      mode="gpu"
      reason="NVIDIA GPU detected but not enough VRAM for the heavier 30B profile"
    fi
  elif [[ "$platform" == "macos" ]]; then
    if [[ "$arch" == "x86_64" ]]; then
      reason="Intel macOS safe default; keep the local model small"
    else
      reason="macOS default kept conservative for easy local setup and broad compatibility"
    fi
  fi

  cat > "$out_file" <<EOF
# Auto-generated by scripts/install-oneclick.sh
BMO_LOCAL_MODEL_PROFILE=$profile
BMO_LOCAL_MODEL_ID=$model_id
BMO_LOCAL_MODEL_FAMILY=$model_family
BMO_LOCAL_MODEL_QUANT=$quant
BMO_LOCAL_MODEL_RUNTIME=$runtime
BMO_LOCAL_MODEL_MODE=$mode
BMO_LOCAL_MODEL_PLATFORM=$platform
BMO_LOCAL_MODEL_ARCH=$arch
BMO_LOCAL_MODEL_RAM_GB=$ram_gb
BMO_LOCAL_MODEL_VRAM_GB=$vram_gb
BMO_LOCAL_MODEL_REASON=$reason
BMO_LOCAL_MODEL_CLOUD_FALLBACK=$cloud_fallback
EOF

  cp "$out_file" "$REPO_DIR/config/local-model.selected.env"
  cat "$out_file"
}

ensure_env_files() {
  say "Writing env files"
  if [[ ! -f "$REPO_DIR/.env" && -f "$REPO_DIR/.env.example" ]]; then
    cp "$REPO_DIR/.env.example" "$REPO_DIR/.env"
  fi
}

ensure_openclaw_cli() {
  say "Ensuring OpenClaw CLI"
  if have_cmd openclaw || [[ -x "$OPENCLAW_PREFIX/bin/openclaw" ]]; then
    echo "OpenClaw already installed."
    return 0
  fi
  curl -fsSL --proto '=https' --tlsv1.2 https://openclaw.ai/install-cli.sh | bash -s -- --prefix "$OPENCLAW_PREFIX" --no-onboard
}

ensure_shell_path_hint() {
  line='export PATH="$HOME/.openclaw/bin:$PATH"'
  for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
    if [[ -f "$rc" ]]; then
      grep -Fqx "$line" "$rc" || printf '\n%s\n' "$line" >> "$rc"
    fi
  done
}

print_summary() {
  say "Install complete"
  echo "repo: $REPO_DIR"
  echo "model profile: $(grep '^BMO_LOCAL_MODEL_PROFILE=' "$REPO_DIR/config/local-model.auto.env" | cut -d= -f2-)"
  echo "model family: $(grep '^BMO_LOCAL_MODEL_FAMILY=' "$REPO_DIR/config/local-model.auto.env" | cut -d= -f2-)"
  echo "reason: $(grep '^BMO_LOCAL_MODEL_REASON=' "$REPO_DIR/config/local-model.auto.env" | cut -d= -f2-)"
  echo ""
  echo "Next recommended checks:"
  echo "  cd $REPO_DIR"
  echo "  make doctor || true"
  echo ""
  echo "If Docker is not installed yet, install Docker Desktop later for sandbox and auxiliary-service features."
}

ensure_repo
ensure_env_files
write_local_model_auto_env
ensure_openclaw_cli
ensure_shell_path_hint
print_summary
